### ISSUE TITLE
Como processar múltiplos produtos no carrinho?

### ISSUE THREAD

**Issue by ghost** [luannsr12/picpay-php#2]
Utilizando a API não diz sobre múltiplos produtos no carrinho, apenas diz sobre um Identificador único do seu pedido.

Como processar mais de um produto, gerando um valor total, como saber quais produtos foram pedidos?

**Comment by marcelloinfoweb** [comment]
Isso vai depender do sistema que voce esta usando, normalmente os sistemas, opencart e magento, eles geram somente um identificador e valor total na ordem de compra, onde descrimina os produtos.
