### ISSUE TITLE
substituir por variaveis para pegar de um banco de dados mysql

### ISSUE THREAD

**Issue by cleitonme** [luannsr12/picpay-php#3]
Amigo desculpe a pergunta. mas não sou um especialista em php..

Como uso uma variavel aqui por exemplo

private $x_picpay_token = "Seu x-picpay-token";

private $x_picpay_token = $token;

**Comment by luannsr12** [comment]
Você pode instanciar a classe passando os valores da variável.
```php
 require_once 'src/paymentPicPay.php';
 $picpay = new PicPay("x_picpay_token","x_seller_token");
```
Agora na Classe você coloca assim:

```php

function __construct($x_picpay_token=0,$x_seller_token=0) {

    $this->x_picpay_token = $x_picpay_token;
    $this->x_seller_token   = $x_seller_token;
  }

```

E apaga a  **private $x_picpay_token** e a **private $x_seller_token**

Pode dar uma conferida aqui: https://pt.stackoverflow.com/questions/56474/php-como-passar-valores-de-atributos-entre-as-classes
